### ISSUE TITLE
Unable to fetch MAC addresses v1.2.0

### ISSUE THREAD

**Issue by BradTX77** [jhurliman/homebridge-motionblinds#10]
I installed this plugin on HOOBS v4 recently, and only one of my 11 shades appeared as accessories upon initial launch. How can I get the MAC addresses for the remaining 10 shades?

Here is the log message:

```
8/27/2021, 12:47:35 PMMotionblinds BridgeLoaded plugin 'homebridge-motionblinds'
8/27/2021, 12:47:35 PMMotionblinds BridgeLoading 1 platforms...
8/27/2021, 12:47:35 PMMotionblinds BridgeMOTION BlindsLoading accessory from cache: [MAC address for one shade  here, hidden by me]
8/27/2021, 12:47:35 PMMotionblinds BridgeBridge is running on port 51836.
8/27/2021, 12:47:38 PMMotionblinds BridgeMOTION BlindsERRORFailed fetching list of MOTION Blinds: Error: timed out after 3 seconds
    at Timeout._onTimeout (/var/lib/hoobs/motionblindsbridge/node_modules/motionblinds/src/index.ts:414:16)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
```

**Comment by jhurliman** [comment]
This should be fixed with the retry logic in 2.0.0.
